WindowManager:
    HomePage:
    SideBarPage:
    AboutUsPage:
    QuitAppPage:
    SendDataPage:
    SeeDataPage:

<ScaleLabel@Label>:
	_scale: 1. if self.texture_size[0] < self.width else float(self.width) / self.texture_size[0]
	canvas.before:
		PushMatrix
		Scale:
			origin: self.center
			x: self._scale or 1.
			y: self._scale or 1.
	canvas.after:
		PopMatrix

<-ScaleButton@Button>:
	state_image: self.background_normal if self.state == 'normal' else self.background_down
	disabled_image: self.background_disabled_normal if self.state == 'normal' else self.background_disabled_down
	_scale: 1. if self.texture_size[0] < self.width else float(self.width) / self.texture_size[0]
	canvas:
		Color:
			rgba: self.background_color
		BorderImage:
			border: self.border
			pos: self.pos
			size: self.size
			source: self.disabled_image if self.disabled else self.state_image
		PushMatrix
		Scale:
			origin: self.center
			x: self._scale or 1.
			y: self._scale or 1.
		Color:
			rgba: self.disabled_color if self.disabled else self.color
		Rectangle:
			texture: self.texture
			size: self.texture_size
			pos: int(self.center_x - self.texture_size[0] / 2.), int(self.center_y - self.texture_size[1] / 2.)
		PopMatrix

<HomePage>:
    name: "home"
    statusLabel : status

    ScaleButton:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "left"
    ScaleButton:
        pos_hint: {"center_x":0.5, "center_y": 0.8 }
        size_hint: 0.7, 0.2
        text: "CoronaCatcher (Click to check mac)"
        on_release:
            root.calculateMac()
    ScaleLabel:
        pos_hint: {"center_x": 0.5, "center_y": 0.6}
        size_hint: 0.7, 0.1
        text: root.actualMac
    ScaleLabel:
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        size_hint: 0.7, 0.1
        text: "Your Mac: " + root.selfMacAddress
    ScaleLabel:
        id: status
        pos_hint: {"center_x": 0.5, "bottom": 0}
        text: root.store.get("statusLabel")["home"]
        size_hint: 1, 0.05




<SideBarPage>:
    name: "sidebar"
    GridLayout:
        cols: 1

        ScaleButton:
            text: "Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"

        ScaleButton:
            text: "About Us"
            on_release:
                app.root.current = "aboutus"
                root.manager.transition.direction = "left"

        ScaleButton:
            text: "My MAC Addresses"
            on_release:
                app.root.current = "seedata"
                root.manager.transition.direction = "left"

        ScaleButton:
            text: "Delete Data & Quit"
            on_release:
                app.root.current = "quitapp"
                root.manager.transition.direction = "left"

        ScaleButton:
            text: "I'm Infected"
            on_release:
                app.root.current = "senddata"
                root.manager.transition.direction = "left"




<AboutUsPage>:
    name: "aboutus"

    ScaleButton:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "right"
    ScaleLabel:
        pos_hint: {"center_x": 0.5, "center_y": 0.8}
        size_hint: 0.4, 0.1
        text: "Our Team"

    ScaleLabel:
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        size_hint: 0.4, 0.8
        text: "We are a team of cool students :/"
        outline_color : 100, 0, 0





<QuitAppPage>:
    name: "quitapp"
    statusLabel : status
    ScaleButton:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "right"



    ScaleButton:
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        size_hint: 0.7, 0.12
        text: "Delete Data"
        on_release:
            root.deleteDataAndQuitButtonClicked()
    ScaleLabel:
        id: status
        pos_hint: {"center_x": 0.5, "bottom": 0}
        text: root.store.get("statusLabel")["quitapp"]
        size_hint: 1, 0.05



<SendDataPage>:
    name: "senddata"
    statusLabel : status
    ScaleButton:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "right"

    ScaleButton:
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        size_hint: 0.7, 0.12
        text: "I'm Infected"
        on_release:
            root.imInfectedButtonClicked()
    ScaleButton:
        pos_hint: {"center_x": 0.5, "center_y": 0.55}
        size_hint: 0.7, 0.12
        text: "I just recovered"
        on_release:
            root.iJustRecoveredButtonClicked()
    ScaleLabel:
        id: status
        pos_hint: {"center_x": 0.5, "bottom": 0}
        text: root.store.get("statusLabel")["senddata"]
        size_hint: 1, 0.05


<SeeDataPage>:
    name: "seedata"

    ScaleButton:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "right"

    ScaleButton:
        pos_hint: {"right": 0.95, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Renew"
        on_release:
            root.renewRecentTen()
